### PR TITLE
Add redirects for mailhog ports, fixes #10

### LINKED ISSUE #10: ddev launch -m shortcut for mailhog doesn't work when ddev/varnish enabled
For projects which use mailhog the ddev-varnish add-on causes `ddev launch -m` to stop working since mailhog is no longer available on the expected URL. The launch command isn't the important but it's pretty neat.

*Workaround*: Access mailhog on novarnish.* URL. 

*Discussion*: Off the top of my head, without knowing all that much about internals, 3 options: a) document as gotcha in README; b) have router handle port 8026 differently; c) handle port 8026 on varnish container, e.g. have Varnish listen on that port too and just pass requests along to web container on same port, or direct to novarish.* URL, or use something like socat to relay the traffic. 

### STEPS TO REPRODUCE:

**Outline**

1. Create a very simple ddev project.
2. Start ddev
3. Launch mailhog: there it is!
4. Add ddev-varnish
5. Restart ddev 
6. Launch mailhog: '503: No ddev back-end site available.'

**Worked example with output**

$ ddev version
 ITEM             VALUE
 DDEV version     v1.21.3
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.3
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.3
 docker           20.10.20
 docker-compose   v2.10.2
 docker-platform  docker-desktop
 mutagen          0.16.0
 os               darwin
 router           drud/ddev-router:v1.21.3
 web              drud/ddev-webserver:v1.21.3

$ ddev poweroff
$ mkdir /tmp/testddev
$ cd /tmp/testddev
$ ddev config --auto
$ printf "<?php\nphpinfo();\n" > index.php
$ ddev start
...
Successfully started testddev
Project can be reached at https://testddev.ddev.site https://127.0.0.1:62323

$ ddev launch -m 

Opens Mailhog at https://testddev.ddev.site:8026 with system default browser.

$ ddev get drud/ddev-varnish && ddev restart
$ ddev restart

$ ddev launch -m 

Still opens https://testddev.ddev.site:8026 with system default browser but now it's an error page from the router container: "502: Unresponsive/broken ddev back-end site."

### PR DESCRIPTION
**Pull request by skeemer**
This is one possible solution for fixing 
* #10.

This seemed the best option to not interfere with other addons.

### CODE REVIEW

**Comment by skeemer** [comment]
How do I make the test "install from release" pass without the PR being merged and released?

**Comment by rfay** [comment]
Just edit it out and then remember to fix :)

**Comment by skeemer** [comment]
So one PR to add the feature and a second PR to be added after the feature is released to fix the tests? That seems a bit convoluted.

**Comment by rfay** [comment]
Could you please manually test and review this @jedebois ?

**Comment by rfay** [comment]
Ping @jedubois

**Review by jedubois — APPROVED** [review]

**Pull request merged**
